// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth/auth.proto

/*
Package auth is a generated protocol buffer package.

It is generated from these files:
	auth/auth.proto

It has these top-level messages:
	VerifyRequest
	VerifyResponse
	GetDetailRequest
	GetDetailResponse
	AuthenticatePasswordRequest
	VerifyPasswordResponse
	CreateUserRequest
*/
package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//
// import "google/protobuf/empty.proto";
// import "google/protobuf/duration.proto";
// import "examples/sub/message.proto";
// import "examples/sub2/message.proto";
// import "google/protobuf/timestamp.proto";
type VerifyRequest struct {
	Token string `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
}

func (m *VerifyRequest) Reset()                    { *m = VerifyRequest{} }
func (m *VerifyRequest) String() string            { return proto.CompactTextString(m) }
func (*VerifyRequest) ProtoMessage()               {}
func (*VerifyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *VerifyRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VerifyResponse struct {
	UserID string `protobuf:"bytes,1,opt,name=UserID" json:"UserID,omitempty"`
}

func (m *VerifyResponse) Reset()                    { *m = VerifyResponse{} }
func (m *VerifyResponse) String() string            { return proto.CompactTextString(m) }
func (*VerifyResponse) ProtoMessage()               {}
func (*VerifyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *VerifyResponse) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetDetailRequest struct {
	UserID string `protobuf:"bytes,1,opt,name=UserID" json:"UserID,omitempty"`
}

func (m *GetDetailRequest) Reset()                    { *m = GetDetailRequest{} }
func (m *GetDetailRequest) String() string            { return proto.CompactTextString(m) }
func (*GetDetailRequest) ProtoMessage()               {}
func (*GetDetailRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetDetailRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetDetailResponse struct {
	UserID    string `protobuf:"bytes,1,opt,name=UserID" json:"UserID,omitempty"`
	Email     string `protobuf:"bytes,2,opt,name=Email" json:"Email,omitempty"`
	FirstName string `protobuf:"bytes,3,opt,name=FirstName" json:"FirstName,omitempty"`
	LastName  string `protobuf:"bytes,4,opt,name=LastName" json:"LastName,omitempty"`
	// only set when creating users
	Password string `protobuf:"bytes,5,opt,name=Password" json:"Password,omitempty"`
}

func (m *GetDetailResponse) Reset()                    { *m = GetDetailResponse{} }
func (m *GetDetailResponse) String() string            { return proto.CompactTextString(m) }
func (*GetDetailResponse) ProtoMessage()               {}
func (*GetDetailResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetDetailResponse) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetDetailResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetDetailResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *GetDetailResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *GetDetailResponse) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthenticatePasswordRequest struct {
	Email    string `protobuf:"bytes,1,opt,name=Email" json:"Email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password" json:"Password,omitempty"`
}

func (m *AuthenticatePasswordRequest) Reset()                    { *m = AuthenticatePasswordRequest{} }
func (m *AuthenticatePasswordRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthenticatePasswordRequest) ProtoMessage()               {}
func (*AuthenticatePasswordRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AuthenticatePasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthenticatePasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type VerifyPasswordResponse struct {
	User  *GetDetailResponse `protobuf:"bytes,1,opt,name=User" json:"User,omitempty"`
	Token string             `protobuf:"bytes,2,opt,name=Token" json:"Token,omitempty"`
}

func (m *VerifyPasswordResponse) Reset()                    { *m = VerifyPasswordResponse{} }
func (m *VerifyPasswordResponse) String() string            { return proto.CompactTextString(m) }
func (*VerifyPasswordResponse) ProtoMessage()               {}
func (*VerifyPasswordResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *VerifyPasswordResponse) GetUser() *GetDetailResponse {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *VerifyPasswordResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type CreateUserRequest struct {
	// e.g. cnw
	UserName string `protobuf:"bytes,1,opt,name=UserName" json:"UserName,omitempty"`
	// e.g. junkmail@conradwood.net
	Email     string `protobuf:"bytes,2,opt,name=Email" json:"Email,omitempty"`
	FirstName string `protobuf:"bytes,3,opt,name=FirstName" json:"FirstName,omitempty"`
	LastName  string `protobuf:"bytes,4,opt,name=LastName" json:"LastName,omitempty"`
	Password  string `protobuf:"bytes,5,opt,name=Password" json:"Password,omitempty"`
}

func (m *CreateUserRequest) Reset()                    { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()               {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CreateUserRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *CreateUserRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*VerifyRequest)(nil), "auth.VerifyRequest")
	proto.RegisterType((*VerifyResponse)(nil), "auth.VerifyResponse")
	proto.RegisterType((*GetDetailRequest)(nil), "auth.GetDetailRequest")
	proto.RegisterType((*GetDetailResponse)(nil), "auth.GetDetailResponse")
	proto.RegisterType((*AuthenticatePasswordRequest)(nil), "auth.AuthenticatePasswordRequest")
	proto.RegisterType((*VerifyPasswordResponse)(nil), "auth.VerifyPasswordResponse")
	proto.RegisterType((*CreateUserRequest)(nil), "auth.CreateUserRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AuthenticationService service

type AuthenticationServiceClient interface {
	// authenticate a user by username/password, return token
	AuthenticatePassword(ctx context.Context, in *AuthenticatePasswordRequest, opts ...grpc.CallOption) (*VerifyPasswordResponse, error)
	// verify a user by token
	VerifyUserToken(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
	GetUserByToken(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*GetDetailResponse, error)
	GetUserDetail(ctx context.Context, in *GetDetailRequest, opts ...grpc.CallOption) (*GetDetailResponse, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*GetDetailResponse, error)
}

type authenticationServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthenticationServiceClient(cc *grpc.ClientConn) AuthenticationServiceClient {
	return &authenticationServiceClient{cc}
}

func (c *authenticationServiceClient) AuthenticatePassword(ctx context.Context, in *AuthenticatePasswordRequest, opts ...grpc.CallOption) (*VerifyPasswordResponse, error) {
	out := new(VerifyPasswordResponse)
	err := grpc.Invoke(ctx, "/auth.AuthenticationService/AuthenticatePassword", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) VerifyUserToken(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	out := new(VerifyResponse)
	err := grpc.Invoke(ctx, "/auth.AuthenticationService/VerifyUserToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) GetUserByToken(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*GetDetailResponse, error) {
	out := new(GetDetailResponse)
	err := grpc.Invoke(ctx, "/auth.AuthenticationService/GetUserByToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) GetUserDetail(ctx context.Context, in *GetDetailRequest, opts ...grpc.CallOption) (*GetDetailResponse, error) {
	out := new(GetDetailResponse)
	err := grpc.Invoke(ctx, "/auth.AuthenticationService/GetUserDetail", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*GetDetailResponse, error) {
	out := new(GetDetailResponse)
	err := grpc.Invoke(ctx, "/auth.AuthenticationService/CreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AuthenticationService service

type AuthenticationServiceServer interface {
	// authenticate a user by username/password, return token
	AuthenticatePassword(context.Context, *AuthenticatePasswordRequest) (*VerifyPasswordResponse, error)
	// verify a user by token
	VerifyUserToken(context.Context, *VerifyRequest) (*VerifyResponse, error)
	GetUserByToken(context.Context, *VerifyRequest) (*GetDetailResponse, error)
	GetUserDetail(context.Context, *GetDetailRequest) (*GetDetailResponse, error)
	CreateUser(context.Context, *CreateUserRequest) (*GetDetailResponse, error)
}

func RegisterAuthenticationServiceServer(s *grpc.Server, srv AuthenticationServiceServer) {
	s.RegisterService(&_AuthenticationService_serviceDesc, srv)
}

func _AuthenticationService_AuthenticatePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticatePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).AuthenticatePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthenticationService/AuthenticatePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).AuthenticatePassword(ctx, req.(*AuthenticatePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_VerifyUserToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).VerifyUserToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthenticationService/VerifyUserToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).VerifyUserToken(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_GetUserByToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).GetUserByToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthenticationService/GetUserByToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).GetUserByToken(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_GetUserDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).GetUserDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthenticationService/GetUserDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).GetUserDetail(ctx, req.(*GetDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthenticationService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthenticationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthenticationService",
	HandlerType: (*AuthenticationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthenticatePassword",
			Handler:    _AuthenticationService_AuthenticatePassword_Handler,
		},
		{
			MethodName: "VerifyUserToken",
			Handler:    _AuthenticationService_VerifyUserToken_Handler,
		},
		{
			MethodName: "GetUserByToken",
			Handler:    _AuthenticationService_GetUserByToken_Handler,
		},
		{
			MethodName: "GetUserDetail",
			Handler:    _AuthenticationService_GetUserDetail_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _AuthenticationService_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/auth.proto",
}

func init() { proto.RegisterFile("auth/auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0x5d, 0x4f, 0xe2, 0x40,
	0x14, 0x4d, 0xbb, 0x40, 0xe0, 0x6e, 0x80, 0x65, 0x96, 0x65, 0x9b, 0x2e, 0x0f, 0xbb, 0x4d, 0x36,
	0x21, 0x9a, 0x40, 0x82, 0xaf, 0x86, 0xf8, 0x81, 0x12, 0x13, 0xa3, 0x06, 0xbf, 0x1e, 0x7c, 0x1a,
	0xf1, 0x0a, 0x13, 0xa1, 0x83, 0x9d, 0x41, 0xc3, 0x2f, 0xf1, 0xc1, 0x3f, 0xe9, 0x4f, 0x30, 0x33,
	0xd3, 0xd2, 0x2a, 0x16, 0xdf, 0x7c, 0x21, 0x9c, 0x39, 0xe7, 0x9e, 0xdc, 0x7b, 0x4e, 0x0a, 0x65,
	0x3a, 0x93, 0xa3, 0x96, 0xfa, 0x69, 0x4e, 0x03, 0x2e, 0x39, 0xc9, 0xa8, 0xff, 0x6e, 0x7d, 0xc8,
	0xf9, 0x70, 0x8c, 0x2d, 0x3a, 0x65, 0x2d, 0xea, 0xfb, 0x5c, 0x52, 0xc9, 0xb8, 0x2f, 0x8c, 0xc6,
	0xfb, 0x0f, 0xc5, 0x0b, 0x0c, 0xd8, 0xed, 0xbc, 0x8f, 0xf7, 0x33, 0x14, 0x92, 0x54, 0x21, 0x7b,
	0xc6, 0xef, 0xd0, 0x77, 0xac, 0xbf, 0x56, 0xa3, 0xd0, 0x37, 0xc0, 0x6b, 0x40, 0x29, 0x92, 0x89,
	0x29, 0xf7, 0x05, 0x92, 0x1a, 0xe4, 0xce, 0x05, 0x06, 0x07, 0xdd, 0x50, 0x18, 0x22, 0x6f, 0x0d,
	0x7e, 0xf4, 0x50, 0x76, 0x51, 0x52, 0x36, 0x8e, 0x3c, 0xd3, 0xb4, 0x4f, 0x16, 0x54, 0x12, 0xe2,
	0xd5, 0xce, 0x6a, 0xb3, 0xbd, 0x09, 0x65, 0x63, 0xc7, 0x36, 0x9b, 0x69, 0x40, 0xea, 0x50, 0xd8,
	0x67, 0x81, 0x90, 0x47, 0x74, 0x82, 0xce, 0x37, 0xcd, 0xc4, 0x0f, 0xc4, 0x85, 0xfc, 0x21, 0x0d,
	0xc9, 0x8c, 0x26, 0x17, 0x58, 0x71, 0x27, 0x54, 0x88, 0x47, 0x1e, 0xdc, 0x38, 0x59, 0xc3, 0x45,
	0xd8, 0x3b, 0x86, 0x3f, 0xdb, 0x33, 0x39, 0x42, 0x5f, 0xb2, 0x01, 0x95, 0x18, 0xbd, 0x27, 0x42,
	0x32, 0xab, 0x58, 0xc9, 0x55, 0x92, 0x86, 0xf6, 0x3b, 0xc3, 0x2b, 0xa8, 0x99, 0x00, 0x63, 0xab,
	0xf0, 0xdc, 0x75, 0xc8, 0xa8, 0x03, 0xb5, 0xd5, 0xf7, 0xf6, 0xef, 0xa6, 0x2e, 0x70, 0x29, 0x95,
	0xbe, 0x16, 0xc5, 0xed, 0xd8, 0xc9, 0x76, 0x9e, 0x2d, 0xa8, 0xec, 0x06, 0x48, 0x25, 0x2a, 0x51,
	0xb4, 0xa4, 0x0b, 0x79, 0x05, 0xf5, 0xed, 0x66, 0xcf, 0x05, 0xfe, 0xca, 0x2c, 0xdb, 0x2f, 0x36,
	0xfc, 0x4a, 0x84, 0xc9, 0xb8, 0x7f, 0x8a, 0xc1, 0x03, 0x1b, 0x20, 0xb9, 0x84, 0xea, 0x47, 0x29,
	0x93, 0x7f, 0x26, 0x84, 0x15, 0x0d, 0xb8, 0x75, 0x23, 0x49, 0xc9, 0x74, 0x13, 0xca, 0x86, 0x51,
	0x07, 0xeb, 0x8c, 0xc8, 0xcf, 0xe4, 0x40, 0xe4, 0x52, 0x7d, 0xfb, 0x18, 0x4e, 0x77, 0xa0, 0xd4,
	0x43, 0xa9, 0x46, 0x77, 0xe6, 0x2b, 0x86, 0xd3, 0xaa, 0x22, 0x5b, 0x50, 0x0c, 0xe7, 0x0d, 0x41,
	0x6a, 0x4b, 0xca, 0x4f, 0x1c, 0x3a, 0x00, 0x71, 0x9f, 0x24, 0x94, 0x2d, 0x35, 0x9c, 0x3a, 0x7f,
	0x9d, 0xd3, 0x1f, 0xf7, 0xc6, 0x6b, 0x00, 0x00, 0x00, 0xff, 0xff, 0x97, 0xe7, 0x36, 0x96, 0x13,
	0x04, 0x00, 0x00,
}
