// Code generated by protoc-gen-go. DO NOT EDIT.
// source: softcat-rfc-creator/softcat-rfc-creator.proto

/*
Package rfccreator is a generated protocol buffer package.

It is generated from these files:
	softcat-rfc-creator/softcat-rfc-creator.proto

It has these top-level messages:
	OpenPortRequest
	DeleteServerRequest
	FreeTextRequest
	CreateResponse
*/
package rfccreator

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//
// import "google/protobuf/empty.proto";
// import "google/protobuf/duration.proto";
// import "examples/sub/message.proto";
// import "examples/sub2/message.proto";
// import "google/protobuf/timestamp.proto";
type OpenPortRequest struct {
	PortDef       string `protobuf:"bytes,1,opt,name=PortDef" json:"PortDef,omitempty"`
	NicDef        string `protobuf:"bytes,2,opt,name=NicDef" json:"NicDef,omitempty"`
	FromAddr      string `protobuf:"bytes,3,opt,name=FromAddr" json:"FromAddr,omitempty"`
	SendToSoftcat bool   `protobuf:"varint,4,opt,name=SendToSoftcat" json:"SendToSoftcat,omitempty"`
}

func (m *OpenPortRequest) Reset()                    { *m = OpenPortRequest{} }
func (m *OpenPortRequest) String() string            { return proto.CompactTextString(m) }
func (*OpenPortRequest) ProtoMessage()               {}
func (*OpenPortRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *OpenPortRequest) GetPortDef() string {
	if m != nil {
		return m.PortDef
	}
	return ""
}

func (m *OpenPortRequest) GetNicDef() string {
	if m != nil {
		return m.NicDef
	}
	return ""
}

func (m *OpenPortRequest) GetFromAddr() string {
	if m != nil {
		return m.FromAddr
	}
	return ""
}

func (m *OpenPortRequest) GetSendToSoftcat() bool {
	if m != nil {
		return m.SendToSoftcat
	}
	return false
}

type DeleteServerRequest struct {
	Target        string `protobuf:"bytes,1,opt,name=Target" json:"Target,omitempty"`
	SendToSoftcat bool   `protobuf:"varint,2,opt,name=SendToSoftcat" json:"SendToSoftcat,omitempty"`
}

func (m *DeleteServerRequest) Reset()                    { *m = DeleteServerRequest{} }
func (m *DeleteServerRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteServerRequest) ProtoMessage()               {}
func (*DeleteServerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DeleteServerRequest) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *DeleteServerRequest) GetSendToSoftcat() bool {
	if m != nil {
		return m.SendToSoftcat
	}
	return false
}

type FreeTextRequest struct {
	Target        string `protobuf:"bytes,1,opt,name=Target" json:"Target,omitempty"`
	SendToSoftcat bool   `protobuf:"varint,2,opt,name=SendToSoftcat" json:"SendToSoftcat,omitempty"`
	Text          string `protobuf:"bytes,3,opt,name=Text" json:"Text,omitempty"`
}

func (m *FreeTextRequest) Reset()                    { *m = FreeTextRequest{} }
func (m *FreeTextRequest) String() string            { return proto.CompactTextString(m) }
func (*FreeTextRequest) ProtoMessage()               {}
func (*FreeTextRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FreeTextRequest) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *FreeTextRequest) GetSendToSoftcat() bool {
	if m != nil {
		return m.SendToSoftcat
	}
	return false
}

func (m *FreeTextRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type CreateResponse struct {
	NewID string `protobuf:"bytes,1,opt,name=NewID" json:"NewID,omitempty"`
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateResponse) GetNewID() string {
	if m != nil {
		return m.NewID
	}
	return ""
}

func init() {
	proto.RegisterType((*OpenPortRequest)(nil), "rfccreator.OpenPortRequest")
	proto.RegisterType((*DeleteServerRequest)(nil), "rfccreator.DeleteServerRequest")
	proto.RegisterType((*FreeTextRequest)(nil), "rfccreator.FreeTextRequest")
	proto.RegisterType((*CreateResponse)(nil), "rfccreator.CreateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RFCManager service

type RFCManagerClient interface {
	OpenPort(ctx context.Context, in *OpenPortRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	DeleteServer(ctx context.Context, in *DeleteServerRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	FreeText(ctx context.Context, in *FreeTextRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type rFCManagerClient struct {
	cc *grpc.ClientConn
}

func NewRFCManagerClient(cc *grpc.ClientConn) RFCManagerClient {
	return &rFCManagerClient{cc}
}

func (c *rFCManagerClient) OpenPort(ctx context.Context, in *OpenPortRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := grpc.Invoke(ctx, "/rfccreator.RFCManager/OpenPort", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rFCManagerClient) DeleteServer(ctx context.Context, in *DeleteServerRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := grpc.Invoke(ctx, "/rfccreator.RFCManager/DeleteServer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rFCManagerClient) FreeText(ctx context.Context, in *FreeTextRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := grpc.Invoke(ctx, "/rfccreator.RFCManager/FreeText", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RFCManager service

type RFCManagerServer interface {
	OpenPort(context.Context, *OpenPortRequest) (*CreateResponse, error)
	DeleteServer(context.Context, *DeleteServerRequest) (*CreateResponse, error)
	FreeText(context.Context, *FreeTextRequest) (*CreateResponse, error)
}

func RegisterRFCManagerServer(s *grpc.Server, srv RFCManagerServer) {
	s.RegisterService(&_RFCManager_serviceDesc, srv)
}

func _RFCManager_OpenPort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenPortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RFCManagerServer).OpenPort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rfccreator.RFCManager/OpenPort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RFCManagerServer).OpenPort(ctx, req.(*OpenPortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RFCManager_DeleteServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RFCManagerServer).DeleteServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rfccreator.RFCManager/DeleteServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RFCManagerServer).DeleteServer(ctx, req.(*DeleteServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RFCManager_FreeText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FreeTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RFCManagerServer).FreeText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rfccreator.RFCManager/FreeText",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RFCManagerServer).FreeText(ctx, req.(*FreeTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RFCManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rfccreator.RFCManager",
	HandlerType: (*RFCManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenPort",
			Handler:    _RFCManager_OpenPort_Handler,
		},
		{
			MethodName: "DeleteServer",
			Handler:    _RFCManager_DeleteServer_Handler,
		},
		{
			MethodName: "FreeText",
			Handler:    _RFCManager_FreeText_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "softcat-rfc-creator/softcat-rfc-creator.proto",
}

func init() { proto.RegisterFile("softcat-rfc-creator/softcat-rfc-creator.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0xdd, 0x4a, 0xf3, 0x50,
	0x10, 0xfc, 0xd2, 0xaf, 0xd6, 0xba, 0xa8, 0x85, 0x55, 0x4a, 0x88, 0x82, 0x25, 0x88, 0xf4, 0xa6,
	0x2d, 0xe8, 0x13, 0x48, 0x7f, 0xc0, 0x8b, 0x56, 0x49, 0xfa, 0x02, 0xc7, 0x74, 0x13, 0x0a, 0xf5,
	0x6c, 0xdc, 0x1c, 0x7f, 0x5e, 0xc0, 0x87, 0xf5, 0x2d, 0x24, 0xc9, 0xa9, 0xb6, 0xb5, 0xe8, 0x8d,
	0x77, 0x99, 0x9d, 0x65, 0x76, 0x32, 0x73, 0xa0, 0x93, 0x71, 0x6c, 0x22, 0x65, 0x3a, 0x12, 0x47,
	0x9d, 0x48, 0x48, 0x19, 0x96, 0xde, 0x96, 0x59, 0x37, 0x15, 0x36, 0x8c, 0x20, 0x71, 0x64, 0x27,
	0xde, 0x69, 0xc2, 0x9c, 0x2c, 0xa8, 0xa7, 0xd2, 0x79, 0x4f, 0x69, 0xcd, 0x46, 0x99, 0x39, 0xeb,
	0xac, 0xdc, 0xf4, 0xdf, 0x1c, 0x68, 0xdc, 0xa6, 0xa4, 0xef, 0x58, 0x4c, 0x40, 0x8f, 0x4f, 0x94,
	0x19, 0x74, 0x61, 0x37, 0x87, 0x03, 0x8a, 0x5d, 0xa7, 0xe5, 0xb4, 0xf7, 0x82, 0x25, 0xc4, 0x26,
	0xd4, 0x26, 0xf3, 0x28, 0x27, 0x2a, 0x05, 0x61, 0x11, 0x7a, 0x50, 0x1f, 0x09, 0x3f, 0x5c, 0xcf,
	0x66, 0xe2, 0xfe, 0x2f, 0x98, 0x4f, 0x8c, 0xe7, 0x70, 0x10, 0x92, 0x9e, 0x4d, 0x39, 0x2c, 0xed,
	0xba, 0xd5, 0x96, 0xd3, 0xae, 0x07, 0xeb, 0x43, 0x3f, 0x84, 0xa3, 0x01, 0x2d, 0xc8, 0x50, 0x48,
	0xf2, 0x4c, 0xb2, 0xb4, 0xd2, 0x84, 0xda, 0x54, 0x49, 0x42, 0xc6, 0x3a, 0xb1, 0xe8, 0xbb, 0x68,
	0x65, 0x9b, 0x68, 0x04, 0x8d, 0x91, 0x10, 0x4d, 0xe9, 0xd5, 0xfc, 0x89, 0x20, 0x22, 0x54, 0x73,
	0x31, 0xfb, 0x8f, 0xc5, 0xb7, 0x7f, 0x01, 0x87, 0xfd, 0x3c, 0x6a, 0x0a, 0x28, 0x4b, 0x59, 0x67,
	0x84, 0xc7, 0xb0, 0x33, 0xa1, 0x97, 0x9b, 0x81, 0x3d, 0x51, 0x82, 0xcb, 0x77, 0x07, 0x20, 0x18,
	0xf5, 0xc7, 0x4a, 0xab, 0x84, 0x04, 0x87, 0x50, 0x5f, 0xe6, 0x8e, 0x27, 0xdd, 0xaf, 0xbe, 0xba,
	0x1b, 0x6d, 0x78, 0xde, 0x2a, 0xb9, 0x7e, 0xc9, 0xff, 0x87, 0x63, 0xd8, 0x5f, 0xcd, 0x0d, 0xcf,
	0x56, 0xb7, 0xb7, 0x24, 0xfa, 0x8b, 0xdc, 0x30, 0x2f, 0xb2, 0x4c, 0x6c, 0xdd, 0xd5, 0x46, 0x8e,
	0x3f, 0xcb, 0xdc, 0xd7, 0x8a, 0xc7, 0x75, 0xf5, 0x11, 0x00, 0x00, 0xff, 0xff, 0xe0, 0x6b, 0x56,
	0xd3, 0xb7, 0x02, 0x00, 0x00,
}
