// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logservice/logservice.proto

/*
Package logservice is a generated protocol buffer package.

It is generated from these files:
	logservice/logservice.proto

It has these top-level messages:
	LogAppDef
	LogLine
	LogRequest
	LogResponse
	LogFilter
	GetLogRequest
	LogEntry
	GetLogResponse
*/
package logservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LogAppDef struct {
	Status       string `protobuf:"bytes,1,opt,name=Status" json:"Status,omitempty"`
	Appname      string `protobuf:"bytes,2,opt,name=Appname" json:"Appname,omitempty"`
	Repository   string `protobuf:"bytes,3,opt,name=Repository" json:"Repository,omitempty"`
	Groupname    string `protobuf:"bytes,4,opt,name=Groupname" json:"Groupname,omitempty"`
	Namespace    string `protobuf:"bytes,5,opt,name=Namespace" json:"Namespace,omitempty"`
	DeploymentID string `protobuf:"bytes,6,opt,name=DeploymentID" json:"DeploymentID,omitempty"`
	StartupID    string `protobuf:"bytes,7,opt,name=StartupID" json:"StartupID,omitempty"`
}

func (m *LogAppDef) Reset()                    { *m = LogAppDef{} }
func (m *LogAppDef) String() string            { return proto.CompactTextString(m) }
func (*LogAppDef) ProtoMessage()               {}
func (*LogAppDef) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LogAppDef) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *LogAppDef) GetAppname() string {
	if m != nil {
		return m.Appname
	}
	return ""
}

func (m *LogAppDef) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

func (m *LogAppDef) GetGroupname() string {
	if m != nil {
		return m.Groupname
	}
	return ""
}

func (m *LogAppDef) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *LogAppDef) GetDeploymentID() string {
	if m != nil {
		return m.DeploymentID
	}
	return ""
}

func (m *LogAppDef) GetStartupID() string {
	if m != nil {
		return m.StartupID
	}
	return ""
}

type LogLine struct {
	Time int64  `protobuf:"varint,1,opt,name=Time" json:"Time,omitempty"`
	Line string `protobuf:"bytes,2,opt,name=Line" json:"Line,omitempty"`
}

func (m *LogLine) Reset()                    { *m = LogLine{} }
func (m *LogLine) String() string            { return proto.CompactTextString(m) }
func (*LogLine) ProtoMessage()               {}
func (*LogLine) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LogLine) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *LogLine) GetLine() string {
	if m != nil {
		return m.Line
	}
	return ""
}

type LogRequest struct {
	AppDef *LogAppDef `protobuf:"bytes,1,opt,name=AppDef" json:"AppDef,omitempty"`
	Lines  []*LogLine `protobuf:"bytes,2,rep,name=Lines" json:"Lines,omitempty"`
}

func (m *LogRequest) Reset()                    { *m = LogRequest{} }
func (m *LogRequest) String() string            { return proto.CompactTextString(m) }
func (*LogRequest) ProtoMessage()               {}
func (*LogRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LogRequest) GetAppDef() *LogAppDef {
	if m != nil {
		return m.AppDef
	}
	return nil
}

func (m *LogRequest) GetLines() []*LogLine {
	if m != nil {
		return m.Lines
	}
	return nil
}

type LogResponse struct {
}

func (m *LogResponse) Reset()                    { *m = LogResponse{} }
func (m *LogResponse) String() string            { return proto.CompactTextString(m) }
func (*LogResponse) ProtoMessage()               {}
func (*LogResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type LogFilter struct {
	Host     string     `protobuf:"bytes,1,opt,name=Host" json:"Host,omitempty"`
	UserName string     `protobuf:"bytes,2,opt,name=UserName" json:"UserName,omitempty"`
	AppDef   *LogAppDef `protobuf:"bytes,3,opt,name=AppDef" json:"AppDef,omitempty"`
}

func (m *LogFilter) Reset()                    { *m = LogFilter{} }
func (m *LogFilter) String() string            { return proto.CompactTextString(m) }
func (*LogFilter) ProtoMessage()               {}
func (*LogFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *LogFilter) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *LogFilter) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LogFilter) GetAppDef() *LogAppDef {
	if m != nil {
		return m.AppDef
	}
	return nil
}

type GetLogRequest struct {
	// logical OR of stuff to retrieve - if null means EVERYTHING
	LogFilter []*LogFilter `protobuf:"bytes,1,rep,name=LogFilter" json:"LogFilter,omitempty"`
	// minimum logid to retrieve (0=all) (negative means last n lines)
	MinimumLogID int64 `protobuf:"varint,2,opt,name=MinimumLogID" json:"MinimumLogID,omitempty"`
}

func (m *GetLogRequest) Reset()                    { *m = GetLogRequest{} }
func (m *GetLogRequest) String() string            { return proto.CompactTextString(m) }
func (*GetLogRequest) ProtoMessage()               {}
func (*GetLogRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetLogRequest) GetLogFilter() []*LogFilter {
	if m != nil {
		return m.LogFilter
	}
	return nil
}

func (m *GetLogRequest) GetMinimumLogID() int64 {
	if m != nil {
		return m.MinimumLogID
	}
	return 0
}

type LogEntry struct {
	ID       uint64     `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Host     string     `protobuf:"bytes,2,opt,name=Host" json:"Host,omitempty"`
	UserName string     `protobuf:"bytes,3,opt,name=UserName" json:"UserName,omitempty"`
	Occured  uint64     `protobuf:"varint,4,opt,name=Occured" json:"Occured,omitempty"`
	AppDef   *LogAppDef `protobuf:"bytes,5,opt,name=AppDef" json:"AppDef,omitempty"`
	Line     string     `protobuf:"bytes,6,opt,name=Line" json:"Line,omitempty"`
}

func (m *LogEntry) Reset()                    { *m = LogEntry{} }
func (m *LogEntry) String() string            { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()               {}
func (*LogEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *LogEntry) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *LogEntry) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *LogEntry) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LogEntry) GetOccured() uint64 {
	if m != nil {
		return m.Occured
	}
	return 0
}

func (m *LogEntry) GetAppDef() *LogAppDef {
	if m != nil {
		return m.AppDef
	}
	return nil
}

func (m *LogEntry) GetLine() string {
	if m != nil {
		return m.Line
	}
	return ""
}

type GetLogResponse struct {
	Entries []*LogEntry `protobuf:"bytes,1,rep,name=Entries" json:"Entries,omitempty"`
}

func (m *GetLogResponse) Reset()                    { *m = GetLogResponse{} }
func (m *GetLogResponse) String() string            { return proto.CompactTextString(m) }
func (*GetLogResponse) ProtoMessage()               {}
func (*GetLogResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetLogResponse) GetEntries() []*LogEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func init() {
	proto.RegisterType((*LogAppDef)(nil), "logservice.LogAppDef")
	proto.RegisterType((*LogLine)(nil), "logservice.LogLine")
	proto.RegisterType((*LogRequest)(nil), "logservice.LogRequest")
	proto.RegisterType((*LogResponse)(nil), "logservice.LogResponse")
	proto.RegisterType((*LogFilter)(nil), "logservice.LogFilter")
	proto.RegisterType((*GetLogRequest)(nil), "logservice.GetLogRequest")
	proto.RegisterType((*LogEntry)(nil), "logservice.LogEntry")
	proto.RegisterType((*GetLogResponse)(nil), "logservice.GetLogResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for LogService service

type LogServiceClient interface {
	LogCommandStdout(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error)
	GetLogCommandStdout(ctx context.Context, in *GetLogRequest, opts ...grpc.CallOption) (*GetLogResponse, error)
}

type logServiceClient struct {
	cc *grpc.ClientConn
}

func NewLogServiceClient(cc *grpc.ClientConn) LogServiceClient {
	return &logServiceClient{cc}
}

func (c *logServiceClient) LogCommandStdout(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	out := new(LogResponse)
	err := grpc.Invoke(ctx, "/logservice.LogService/LogCommandStdout", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) GetLogCommandStdout(ctx context.Context, in *GetLogRequest, opts ...grpc.CallOption) (*GetLogResponse, error) {
	out := new(GetLogResponse)
	err := grpc.Invoke(ctx, "/logservice.LogService/GetLogCommandStdout", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LogService service

type LogServiceServer interface {
	LogCommandStdout(context.Context, *LogRequest) (*LogResponse, error)
	GetLogCommandStdout(context.Context, *GetLogRequest) (*GetLogResponse, error)
}

func RegisterLogServiceServer(s *grpc.Server, srv LogServiceServer) {
	s.RegisterService(&_LogService_serviceDesc, srv)
}

func _LogService_LogCommandStdout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).LogCommandStdout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logservice.LogService/LogCommandStdout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).LogCommandStdout(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_GetLogCommandStdout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).GetLogCommandStdout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logservice.LogService/GetLogCommandStdout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).GetLogCommandStdout(ctx, req.(*GetLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "logservice.LogService",
	HandlerType: (*LogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LogCommandStdout",
			Handler:    _LogService_LogCommandStdout_Handler,
		},
		{
			MethodName: "GetLogCommandStdout",
			Handler:    _LogService_GetLogCommandStdout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logservice/logservice.proto",
}

func init() { proto.RegisterFile("logservice/logservice.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 487 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x55, 0x92, 0x36, 0x59, 0x6f, 0xb7, 0x09, 0x79, 0x30, 0x4c, 0x41, 0x68, 0xca, 0xd3, 0x78,
	0xa0, 0x88, 0xee, 0x07, 0x98, 0x16, 0x18, 0x91, 0xc2, 0x90, 0x5c, 0xf8, 0x80, 0xd0, 0xde, 0x85,
	0xa0, 0x26, 0x36, 0xb1, 0x83, 0xd4, 0xaf, 0xe1, 0x91, 0x8f, 0xe2, 0x67, 0x50, 0xec, 0x24, 0x75,
	0x03, 0x48, 0x7d, 0xb3, 0xcf, 0xb9, 0x39, 0x39, 0xe7, 0x9e, 0x04, 0x9e, 0x6e, 0x78, 0x26, 0xb1,
	0xfa, 0x91, 0xaf, 0xf0, 0xd5, 0xee, 0x38, 0x17, 0x15, 0x57, 0x9c, 0xc0, 0x0e, 0x09, 0x7f, 0x3b,
	0x30, 0x49, 0x78, 0x76, 0x2d, 0x44, 0x84, 0xf7, 0xe4, 0x1c, 0xfc, 0xa5, 0x4a, 0x55, 0x2d, 0xa9,
	0x73, 0xe1, 0x5c, 0x4e, 0x58, 0x7b, 0x23, 0x14, 0x82, 0x6b, 0x21, 0xca, 0xb4, 0x40, 0xea, 0x6a,
	0xa2, 0xbb, 0x92, 0xe7, 0x00, 0x0c, 0x05, 0x97, 0xb9, 0xe2, 0xd5, 0x96, 0x7a, 0x9a, 0xb4, 0x10,
	0xf2, 0x0c, 0x26, 0xb7, 0x15, 0xaf, 0xcd, 0xb3, 0x23, 0x4d, 0xef, 0x80, 0x86, 0xbd, 0x4b, 0x0b,
	0x94, 0x22, 0x5d, 0x21, 0x1d, 0x1b, 0xb6, 0x07, 0x48, 0x08, 0xc7, 0x11, 0x8a, 0x0d, 0xdf, 0x16,
	0x58, 0xaa, 0x38, 0xa2, 0xbe, 0x1e, 0xd8, 0xc3, 0x1a, 0x85, 0xa5, 0x4a, 0x2b, 0x55, 0x8b, 0x38,
	0xa2, 0x81, 0x51, 0xe8, 0x81, 0xf0, 0x35, 0x04, 0x09, 0xcf, 0x92, 0xbc, 0x44, 0x42, 0x60, 0xf4,
	0x29, 0x2f, 0x50, 0x07, 0xf3, 0x98, 0x3e, 0x37, 0x58, 0xc3, 0xb5, 0x99, 0xf4, 0x39, 0xbc, 0x07,
	0x48, 0x78, 0xc6, 0xf0, 0x7b, 0x8d, 0x52, 0x91, 0x97, 0xe0, 0x9b, 0xd5, 0xe8, 0xe7, 0xa6, 0x8b,
	0x47, 0x73, 0x6b, 0x9b, 0xfd, 0xde, 0x58, 0x3b, 0x44, 0x5e, 0xc0, 0xb8, 0x11, 0x91, 0xd4, 0xbd,
	0xf0, 0x2e, 0xa7, 0x8b, 0xb3, 0xc1, 0x74, 0xc3, 0x31, 0x33, 0x11, 0x9e, 0xc0, 0x54, 0xbf, 0x47,
	0x0a, 0x5e, 0x4a, 0x0c, 0xbf, 0xe9, 0x1a, 0xde, 0xe5, 0x1b, 0x85, 0x55, 0xe3, 0xeb, 0x3d, 0x97,
	0xaa, 0x2d, 0x41, 0x9f, 0xc9, 0x0c, 0x8e, 0x3e, 0x4b, 0xac, 0xee, 0x76, 0x1d, 0xf4, 0x77, 0xcb,
	0xa5, 0x77, 0x80, 0xcb, 0xf0, 0x2b, 0x9c, 0xdc, 0xa2, 0xb2, 0x52, 0x5e, 0x59, 0x2f, 0xa7, 0x8e,
	0xb6, 0x3e, 0x94, 0x30, 0x24, 0xb3, 0x4c, 0x86, 0x70, 0xfc, 0x21, 0x2f, 0xf3, 0xa2, 0x2e, 0x12,
	0x9e, 0xc5, 0x91, 0x36, 0xe5, 0xb1, 0x3d, 0x2c, 0xfc, 0xe5, 0xc0, 0x51, 0xc2, 0xb3, 0xb7, 0xa5,
	0xaa, 0xb6, 0xe4, 0x14, 0xdc, 0x38, 0xd2, 0x99, 0x46, 0xcc, 0x8d, 0xa3, 0x3e, 0xa5, 0xfb, 0x9f,
	0x94, 0xde, 0x20, 0x25, 0x85, 0xe0, 0xe3, 0x6a, 0x55, 0x57, 0xb8, 0xd6, 0x1f, 0xd2, 0x88, 0x75,
	0x57, 0x2b, 0xff, 0xf8, 0x90, 0x96, 0xba, 0xda, 0x7d, 0xab, 0xf6, 0x37, 0x70, 0xda, 0xed, 0xc4,
	0x34, 0x42, 0xe6, 0x10, 0x34, 0xbe, 0x73, 0x94, 0xed, 0x4a, 0x1e, 0x0e, 0x54, 0x75, 0x2a, 0xd6,
	0x0d, 0x2d, 0x7e, 0x3a, 0xfa, 0xcb, 0x59, 0x9a, 0x01, 0x72, 0x03, 0x0f, 0x12, 0x9e, 0xdd, 0xf0,
	0xa2, 0x48, 0xcb, 0xf5, 0x52, 0xad, 0x79, 0xad, 0xc8, 0xf9, 0x40, 0xa1, 0xdd, 0xff, 0xec, 0xf1,
	0x5f, 0x78, 0xeb, 0x21, 0x81, 0x33, 0xe3, 0x6a, 0x5f, 0xe7, 0x89, 0x3d, 0xbf, 0x57, 0xe5, 0x6c,
	0xf6, 0x2f, 0xca, 0xa8, 0x7d, 0xf1, 0xf5, 0xef, 0x7f, 0xf5, 0x27, 0x00, 0x00, 0xff, 0xff, 0xd0,
	0xe4, 0x8e, 0x2b, 0x1d, 0x04, 0x00, 0x00,
}
